# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  static-analysis:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest mypy black bandit pylint
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        fi

    - name: mypy
      if: ${{ always() }}
      run: |
        mypy .                          \
          --ignore-missing-imports      \
          --disallow-untyped-defs       \
          --disallow-untyped-decorators \
          --disallow-incomplete-defs

    - name: flake8
      if: ${{ always() }}
      run: |
        # check line-length without printing source
        flake8 . --count --statistics --select=E501 --max-line-length=127

        # check the rest while printing source
        flake8 . --count --statistics --ignore=E501 --show-source

    - name: pylint
      if: ${{ always() }}
      continue-on-error: true
      run: |
        cd ..
        pylint finance                                        \
          --max-line-length=120                               \
          --disable=missing-docstring,no-member,broad-except  \
          --variable-rgx="^[a-z][a-z0-9]*((_[a-z0-9]+)*)?$"   \
          --argument-rgx="^[a-z][a-z0-9]*((_[a-z0-9]+)*)?$"

    - name: bandit
      if: ${{ always() }}
      run: |
        bandit -r .

    - name: black
      if: ${{ always() }}
      run: |
        black . --check --line-length=120 --target-version=py38 --diff

    - name: pytest
      continue-on-error: true
      if: ${{ success() }}
      run: |
        pytest
        # exit-code 5 (no tests found) is still OK
        if [[ $? == 5 ]]; then
          exit 0;
        fi;
